spring:
    config:
        activate:
            on-profile: default
    data:
        mongodb:
           
            database: studdb
            port: 27017
            host: localhost
            auto-index-creation: true
server:
    port: 8090
    error:
        include-message: always
        include-binding-errors: always
        include-exception: false
springdoc:
  swagger-ui:
    path: /apidoc
    displayRequestDuration: true
    disable-swagger-default-url: true
    csrf:
      enabled: true
    operationsSorter: method #For sorting endpoints by http methods
    tagsSorter: alpha #For sorting tags alphabetically
  api-docs:
    path: /api


---
spring:
    config:
        activate:
            on-profile: test